Locales['en'] = {
    -- Cloakroom
    ['cloakroom'] = 'Съблекалня',
    ['citizen_wear'] = 'Цивилно облекло',
    ['police_wear'] = 'Униформа',
    ['gilet_wear'] = 'Оранжева рефлектна жилетка',
    ['bullet_wear'] = 'Бронежилетка',
    ['no_outfit'] = 'there\' Тази униформа не ти е по размвер',
    ['open_cloackroom'] = 'Натисни ~INPUT_CONTEXT~ за да смениш ~y~дрехите~s~.',
    -- Armory
    ['remove_object'] = 'Махни предмета',
    ['deposit_object'] = 'Депозирай предмет',
    ['get_weapon'] = 'Вземи оръжие от оръжейната',
    ['put_weapon'] = 'Депозирай оръжие в оръжейната',
    ['buy_weapons'] = 'Купи оръжия',
    ['armory'] = 'Оръжейна',
    ['open_armory'] = 'Натисни ~INPUT_CONTEXT~ за да имаш достъп до ~y~оръжейната~s~.',
    ['armory_owned'] = 'оръжия които имаш',
    ['armory_free'] = 'безплатно',
    ['armory_item'] = '$%s',
    ['armory_weapontitle'] = 'Оръжейна - Купи оръжие',
    ['armory_componenttitle'] = 'Оръжейна - Ъпгрейди за оръжия',
    ['armory_bought'] = 'Ти купи това орръжие ~y~%s~s~ за ~g~$%s~s~',
    ['armory_money'] = 'Нямаш достатъчно пари за това оръжие',
    ['armory_hascomponent'] = 'Вечe имаш този ъпгрейд!',
    ['get_weapon_menu'] = 'Оръжейна - вземи оръжие',
    ['put_weapon_menu'] = 'Оръжейна - прибери оръжие',
    -- Vehicles
    ['vehicle_menu'] = 'Патрулни автомобили',
    ['vehicle_blocked'] = 'Всички възможни места за изкарване на автомобила за заети!',
    ['garage_prompt'] = 'Натисни ~INPUT_CONTEXT~ за да имаш достъпш до ~y~Опциите за патрулните автомобили~s~.',
    ['garage_title'] = 'Опции',
    ['garage_stored'] = 'Прибран',
    ['garage_notstored'] = 'Някъде из града е',
    ['garage_storing'] = 'we\'Ние пробваме се да премахнем патрулният автомобил , сигурни ли сте че няма други граждани около вас.',
    ['garage_has_stored'] = 'Патрулният автомобил е прибран в гаража',
    ['garage_has_notstored'] = 'Патрулен автомобил на ваше име не бе намерен',
    ['garage_notavailable'] = 'Патрулният автомобил е в наказателния паркинг.',
    ['garage_blocked'] = 'there\'Всички места са блокирани!',
    ['garage_empty'] = 'Нямаш патрулни автомобили в гаража.',
    ['garage_released'] = 'Твоят патрулен автомобил беше изкаран от гаража.',
    ['garage_store_nearby'] = 'Няма патрулни автомобили наблизко.',
    ['garage_storeditem'] = 'Отвори гараж',
    ['garage_storeitem'] = 'Прибери патрулен автомобил в гаража',
    ['garage_buyitem'] = 'Магазин за патрлуни автомобили',
    ['garage_notauthorized'] = 'you\'Не си допуснат до гаража.',
    ['helicopter_prompt'] = 'Натисни ~INPUT_CONTEXT~ за да получиш достъп до ~y~Гаража за хеликоптер~s~.',
    ['shop_item'] = '$%s',
    ['vehicleshop_title'] = 'Магазни за патлуни автомобили',
    ['vehicleshop_confirm'] = 'Сигурни ли сте че искате да закупите тази патрулка?',
    ['vehicleshop_bought'] = 'Вие закупихте патрулката ~y~%s~s~ за ~r~$%s~s~',
    ['vehicleshop_money'] = 'Нямаш достатъчно пари в теб , за да закупиш тази патрулка',
    ['vehicleshop_awaiting_model'] = 'Тази патрулка вмомента се кара към салона~g~Товари се и се докарва~s~ моля изчакайте',
    ['confirm_no'] = 'Не',
    ['confirm_yes'] = 'Да',
    -- Service
    ['service_max'] = 'Не можеш да влезенеш на смяна, максималният брой полицай е в града: %s/%s',
    ['service_not'] = 'Не си влзенал на смяна! You\'влез първо на смяна.',
    ['service_anonunce'] = 'Информация за смените',
    ['service_in'] = 'you\'вече си на смяна!',
    ['service_in_announce'] = 'Полицаят ~y~%s~s~ влезе на смяна!',
    ['service_out'] = 'Ти излезе от смяна.',
    ['service_out_announce'] = 'Полицаят ~y~%s~s~ изелезе от смяна.',
    -- Action Menu
    ['citizen_interaction'] = 'Действия с гражадани',
    ['vehicle_interaction'] = 'Действия с автомобили',
    ['object_spawner'] = 'поставяне на обекти',
  
    ['id_card'] = 'Провери личността',
    ['search'] = 'Претърси',
    ['handcuff'] = 'Сложи белезници / Махни белезници',
    ['drag'] = 'Ескортирай',
    ['put_in_vehicle'] = 'Вкарай в автомобила',
    ['out_the_vehicle'] = 'Изкарай от автомобила',
    ['fine'] = 'Глоби',
    ['unpaid_bills'] = 'Провери неплатени глоби',
    ['license_check'] = 'Провери лицензите му',
    ['license_revoke'] = 'Конфискувай лиценза му',
    ['license_revoked'] = 'Вашият ~b~%s~s~ беше ~y~конфискуван~s~!',
    ['licence_you_revoked'] = 'Вие конфискувахте ~b~%s~s~ което ще бъде годсно отново след ~y~%s~s~',
    ['no_players_nearby'] = 'Няма граждани наблизо!',
    ['being_searched'] = 'Вие сте ~y~претърсен~s~ от ~b~Полицията~s~',
    -- Vehicle interaction
    ['vehicle_info'] = 'Информация за автомобила',
    ['pick_lock'] = 'отключи превозното средство',
    ['vehicle_unlocked'] = 'Автомобилът е ~g~отключен~s~',
    ['no_vehicles_nearby'] = 'Няма автомобили наблизо',
    ['impound'] = 'Конфискувай превозното средство',
    ['impound_prompt'] = 'Натисни ~INPUT_CONTEXT~ за да спреш ~y~конфискуването на автомобила~s~',
    ['impound_canceled'] = 'Вие спряхте конфискуването на автомобила',
    ['impound_canceled_moved'] = 'Конфискуването беше отквазанао защото превозното средство беше преместено',
    ['impound_successful'] = 'Вие конфикувахте автомобила',
    ['search_database'] = 'Информация за автомобила',
    ['search_database_title'] = 'Потърсете информация през въвеждането на - регистрационен номер',
    ['search_database_error_invalid'] = 'Това ~r~не~s~ е ~y~истински~s~ регистрационен номер',
    -- Traffic interaction
    ['traffic_interaction'] = 'Ограда за спиране на трафика',
    ['cone'] = 'Конус',
    ['barrier'] = 'Бариера',
    ['spikestrips'] = 'Лента от шипове',
    ['box'] = 'Кутия',
    ['cash'] = 'Кутия с пари',
    -- ID Card Menu
    ['name'] = 'Име: %s',
    ['job'] = 'Работа: %s',
    ['sex'] = 'Пол: %s',
    ['dob'] = 'DOB: %s',
    ['height'] = 'Височина: %s',
    ['bac'] = 'BAC: %s',
    ['unknown'] = 'Незнайно',
    ['male'] = 'Мъж',
    ['female'] = 'Жена',
    -- Body Search Menu
    ['guns_label'] = '--- Оръжия ---',
    ['inventory_label'] = '--- Джобове ---',
    ['license_label'] = ' --- Лицензи ---',
    ['confiscate'] = 'Конфискувай %s',
    ['confiscate_weapon'] = 'Конфискувахте %s със %s патрони',
    ['confiscate_inv'] = 'Конфикувахте %sx %s',
    ['confiscate_dirty'] = 'Конфикувахте мръсни пари: <span style="color:red;">$%s</span>',
    ['you_confiscated'] = 'Вие конфикувахте ~y~%sx~s~ ~b~%s~s~ от ~b~%s~s~',
    ['got_confiscated'] = '~y~%sx~s~ ~b~%s~s~ беше конфискувано от ~y~%s~s~',
    ['you_confiscated_account'] = 'Вие конфикувахте ~g~$%s~s~ (%s) от ~b~%s~s~',
    ['got_confiscated_account'] = '~g~$%s~s~ (%s) беше конфискувано от ~y~%s~s~',
    ['you_confiscated_weapon'] = 'Вие конфискувахте ~b~%s~s~ от ~b~%s~s~ със ~o~%s~s~ патрони',
    ['got_confiscated_weapon'] = 'Вашият ~b~%s~s~ със ~o~%s~s~ патрони беше конфискуван от ~y~%s~s~',
    ['traffic_offense'] = 'Пътно нарушение',
    ['minor_offense'] = 'Леко престъпление',
    ['average_offense'] = 'Средно престъпление',
    ['major_offense'] = 'Тежко престъпление',
    ['fine_total'] = 'Цена на всички глоби: %s',
    -- Vehicle Info Menu
    ['plate'] = 'Регистрационен номер: %s',
    ['owner_unknown'] = 'Собственик: Издирва се',
    ['owner'] = 'Собственик: %s',
    -- Boss Menu
    ['open_bossmenu'] = 'Натиснете ~INPUT_CONTEXT~ за да получите достъп до шефското меню',
    ['quantity_invalid'] = 'Невалидна стойност',
    ['have_withdrawn'] = 'Ти изтегли ~y~%sx~s~ ~b~%s~s~',
    ['have_deposited'] = 'Ти депозира ~y~%sx~s~ ~b~%s~s~',
    ['quantity'] = 'Стойност',
    ['inventory'] = 'Хазна',
    ['police_stock'] = 'Стока в полицейската хазна',
    -- Misc
    ['remove_prop'] = 'Натисни ~INPUT_CONTEXT~ за да вземеш обекта',
    ['map_blip'] = 'РПУ',
    ['unrestrained_timer'] = 'Започваш да усещаш че белезниците бавно започват да се махат от ръцете ти.',
    -- Notifications
    ['alert_police'] = 'Сигнал',
    ['phone_police'] = 'Полиция',
  }
  